align with setup/environment changes from update branch

diff --git a/bin/hooks/pre-commit b/bin/hooks/pre-commit
--- a/bin/hooks/pre-commit
+++ b/bin/hooks/pre-commit
@@ -1,56 +1,81 @@
 #!/usr/bin/env bash
 
 
-render_usage_docs() {
+main() {
 	local git_root="$(git rev-parse --show-toplevel)"
-	# install git-flux from source to get the local changes in the help output
+
+	# uncomment this line if you want to see the logs
+#	exec &> ${git_root}/pre-commit.log
+
+	log "first, stash index and work dir, keeping only the to-be-committed changes in the working directory."
+	local old_stash=$(git rev-parse -q --verify refs/stash)
+	save_stash
+	local new_stash=$(git rev-parse -q --verify refs/stash)
+
+	if [ "$old_stash" = "$new_stash" ]; then
+		log "nothing was stashed, this means there were no changes (e.g. '--amend', '--allow-empty'), so skip everything."
+		exit 0
+	fi
+	
+	log "get real changes of the commit to be done."
+	local changed_files=$(git diff --cached --name-only --diff-filter=ACDM "$(against_revision)")
+	log "changed files:"
+	echo "$changed_files"
+
+	log "we want to add some changes to the staged area later, so unstash beforehand."
+	restore_stash
+
+	log "set default status as success"
+	local status=0
+	
+	log "look for changes in files that are known to affect the help output (public files)."
+	if [[ $changed_files =~ git-flux* ]]; then
+		log "there are changes in public files, rendering usage docs."
+		generate_usage_docs "$git_root"
+		status=$?
+	fi
+
+	log "exit with status $status."
+	exit $status # nonzero prevents commit
+}
+
+save_stash() {
+	git stash save -q --keep-index
+}
+
+restore_stash() {
+	log "don't let internal git-stash implementation stand in our way: set config to ignore trailing-whitespace errors on git-apply"
+	git config core.whitespace -trailing-space
+	log "restore changes from stash"
+	git reset --hard -q && git stash apply --index -q && git stash drop -q
+	log "restore previous config"
+	git config --unset core.whitespace -trailing-space
+}
+
+generate_usage_docs() {
+	local git_root="$1"
+	log "install git-flux from source to get the local changes in the help output"
 	${git_root}/bin/setup-dev.sh update || { return 1; }
-	# render usage docs
+	log "render usage docs"
 	${git_root}/bin/usage.sh || { return 2; }
+	log "add change to index (stage area)"
+	git add -v ${git_root}/usage || { return 3; }
 	return 0
 }
 
 against_revision() {
 	local against
 	if git rev-parse --verify HEAD >/dev/null 2>&1; then
-	    against=HEAD
+		against=HEAD
 	else
-	    # Initial commit: diff against an empty tree object
-	    against=$(git hash-object -t tree /dev/null)
+		# initial commit: diff against an empty tree object
+		against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 	fi
 	printf "%s" "$against"
 }
 
-
-main() {
-
-	# first, stash index and work dir, keeping only the
-	# to-be-committed changes in the working directory.
-	local old_stash=$(git rev-parse -q --verify refs/stash)
-	git stash save -q --keep-index
-	local new_stash=$(git rev-parse -q --verify refs/stash)
-
-	# if there were no changes (e.g., `--amend` or `--allow-empty`)
-	# then nothing was stashed, and we should skip everything.
-	if [ "$old_stash" = "$new_stash" ]; then
-	    exit 0
-	fi
-
-
-	# do stuff
-	local status=0
-
-	local changed_files=$(git diff --cached --name-only --diff-filter=ACDM "$(against_revision)")
-	if [[ $changed_files =~ git-flux* ]]; then
-		render_usage_docs
-		status=$?
-	fi
-
-	# restore changes
-	git reset --hard -q && git stash apply --index -q && git stash drop -q
-
-	# exit with status from the stuff we did: nonzero prevents commit
-	exit $status
+log() {
+	echo " > $1"
 }
 
 
