testing pre-commit hook setup

diff --git a/bin/hooks/pre-commit_ b/bin/hooks/pre-commit_
--- a/bin/hooks/pre-commit_
+++ b/bin/hooks/pre-commit_
@@ -31,31 +31,41 @@
 
 
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-    against=HEAD
-else
-    # initial commit: diff against an empty tree object
-    against=$(git hash-object -t tree /dev/null)
-fi
 
-create_temp_dir() {
+create_temp_file() {
 	mktemp 2>/dev/null || mktemp -t 'pre-commit-hook-changes'
 }
 
 cleanup() {
-	rm -f "$1"
+	echo "deleting [$1]"
+#	rm -f "$1"
 }
 
 create_patch() {
-	git diff --exit-code --binary --ignore-submodules --no-color > "$1"
+	git diff --exit-code --binary --ignore-submodules --no-color > $1
 }
 
-patch_filename=$(create_temp_dir)
+#patch_filename="$(create_temp_file)"
+#echo "patch_filename: $patch_filename"
+#trap 'cleanup '"$patch_filename" EXIT
 
-trap 'cleanup '"$patch_filename" EXIT
 
-create_patch "$patch_filename"
+
+
+
+
+
+
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+    against=HEAD
+else
+    # Initial commit: diff against an empty tree object
+    against=$(git hash-object -t tree /dev/null)
+fi
+
+patch_filename=$(mktemp -t commit_hook_changes.XXXXXX)
+git diff --exit-code --binary --ignore-submodules --no-color > $patch_filename
 has_unstaged_changes=$?
 
 if [ $has_unstaged_changes -ne 0 ]; then
@@ -79,17 +89,14 @@ quit() {
 # Redirect output to stderr.
 exec 1>&2
 
-#files_with_nocommit=$(git diff --cached --name-only --diff-filter=ACM ${against} | xargs grep -i "nocommit" -l | tr '\n' ' ')
+files_with_nocommit=$(git diff --cached --name-only --diff-filter=ACM $against | xargs grep -i "nocommit" -l | tr '\n' ' ')
 
-files_diff=$(git diff --cached --name-only --diff-filter=ACM ${against})
-echo "files diff: $files_diff"
-
-#if [ "x${files_with_nocommit}x" != "xx" ]; then
-#    tput setaf 1
-#    echo "File being committed with 'nocommit' in it:"
-#    echo $files_with_nocommit | tr ' ' '\n'
-#    tput sgr0
-#    quit 1
-#fi
+if [ "x${files_with_nocommit}x" != "xx" ]; then
+    tput setaf 1
+    echo "File being committed with 'nocommit' in it:"
+    echo $files_with_nocommit | tr ' ' '\n'
+    tput sgr0
+    quit 1
+fi
 
 quit 0
